name: CompressedBlocks
version: '1.0.0'
main: com.nico.compressedblocks.CompressedBlocksPlugin
api-version: '26.1'
author: nicogtdm
description: Comprime y descomprime bloques/items en bloques mas densos (9:1 por nivel) usando crafteo vanilla.

commands:
  compressedblocks:
    description: Recarga la configuracion de CompressedBlocks.
    usage: /<command> reload
    permission: compressedblocks.admin
    aliases: [cb]

permissions:
  compressedblocks.admin:
    description: Permite recargar la configuracion de CompressedBlocks.
    default: op
